# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Obojobo User Documentation
email: techrangers@ucf.exclude
description: >- # this means to ignore newlines until "baseurl:"
  Learning Objects, Reinvented
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ucfopen.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: materia_ucf
github_username:  ucfopen

production_url : //ucfopen.github.io/Obojobo-Docs/

# All links will be namespaced by BASE_PATH if defined.
# Links in your website should always be prefixed with {{BASE_PATH}}
# however this value will be dynamically changed depending on your deployment situation.
#
# CNAME (http://yourcustomdomain.com)
#   DO NOT SET BASE_PATH
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Pages (http://username.github.com)
#   DO NOT SET BASE_PATH
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Project Pages (http://username.github.com/project-name)
#
#   A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
#  REQUIRED! Set BASE_PATH to: http://username.github.com/project-name
#
# CAUTION:
#   - When in Localhost, your site will run from root "/" regardless of BASE_PATH
#   - Only the following values are falsy: ["", null, false]
#   - When setting BASE_PATH it must be a valid url.
#     This means always setting the protocol (http|https) or prefixing with "/"
BASE_PATH : //ucfopen.github.io/Obojobo-Docs/

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-menus
  - jekyll-toc

toc:
  min_level: 1 # default: 1
  max_level: 3 # default: 6

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      toc: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
